In [36]:
import numpy as np
import pandas as pd

In [37]:
file = 'E:/NLP Personal Practise/Assignments/IMDB Dataset.csv';
df = pd.read_csv(file)
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [38]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [39]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [40]:
df.duplicated().sum()

418

In [41]:
df.drop_duplicates(inplace=True)

In [42]:
df.duplicated().sum()

0

In [43]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [44]:
df['review'] = df['review'].apply(remove_tags)

In [45]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [46]:
import re
def remove_links(raw_text):
    cleaned_text = re.sub(re.compile(r'https?//\S+|www\.\S+'), '', raw_text)
    return cleaned_text

In [47]:
df['review'] = df['review'].apply(remove_links)

In [48]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [49]:
df['review'] = df['review'].str.lower()

In [50]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [51]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

def remove_stopwords(text):
    words = text.split()
    filtered_words = [item for item in words if item not in sw_list]
    return " ".join(filtered_words)

df['review'] = df['review'].apply(remove_stopwords)
df

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
49995  thought movie right good job. creative origina...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  i'm going disagree previous comment side malti...  negative
49999  one expects star trek movies high art, fans ex...  negative

[49582 rows x 2 columns]

In [52]:
#nltk.download('punkt')

In [225]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
df['review'] = df['review'].apply(sent_tokenize)

In [226]:
tokenized_reviews = []
for sentences in df['review']:
    tokenized_sentences = []
    for sentence in sentences:
        tokenized_words = word_tokenize(sentence)
        tokenized_sentences.append(tokenized_words)
    tokenized_reviews.append(tokenized_sentences)
    
df['review'] = tokenized_reviews
df

review sentiment
0      [[one, reviewers, mentioned, watching, 1, oz, ...  positive
1      [[wonderful, little, production, .], [filming,...  positive
2      [[thought, wonderful, way, spend, time, hot, s...  positive
3      [[basically, there, 's, family, little, boy, (...  negative
4      [[petter, mattei, 's, ``, love, time, money, '...  positive
...                                                  ...       ...
49995  [[thought, movie, right, good, job, .], [creat...  positive
49996  [[bad, plot, ,, bad, dialogue, ,, bad, acting,...  negative
49997  [[catholic, taught, parochial, elementary, sch...  negative
49998  [[i, 'm, going, disagree, previous, comment, s...  negative
49999  [[one, expects, star, trek, movies, high, art,...  negative

[49582 rows x 2 columns]

In [227]:
for i, column in enumerate(df['review']):
    flat_list = []
    for sublist in column:
        flat_list.extend(sublist)
    df['review'][i] = flat_list
df

review sentiment
0      [one, reviewers, mentioned, watching, 1, oz, e...  positive
1      [wonderful, little, production, ., filming, te...  positive
2      [thought, wonderful, way, spend, time, hot, su...  positive
3      [basically, there, 's, family, little, boy, (,...  negative
4      [petter, mattei, 's, ``, love, time, money, ''...  positive
...                                                  ...       ...
49995  [[thought, movie, right, good, job, .], [creat...  positive
49996  [[bad, plot, ,, bad, dialogue, ,, bad, acting,...  negative
49997  [[catholic, taught, parochial, elementary, sch...  negative
49998  [[i, 'm, going, disagree, previous, comment, s...  negative
49999  [[one, expects, star, trek, movies, high, art,...  negative

[49582 rows x 2 columns]

In [228]:
df['review'][0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 '.',
 'right',
 ',',
 'exactly',
 'happened',
 'me.the',
 'first',
 'thing',
 'struck',
 'oz',
 'brutality',
 'unflinching',
 'scenes',
 'violence',
 ',',
 'set',
 'right',
 'word',
 'go',
 '.',
 'trust',
 'me',
 ',',
 'show',
 'faint',
 'hearted',
 'timid',
 '.',
 'show',
 'pulls',
 'punches',
 'regards',
 'drugs',
 ',',
 'sex',
 'violence',
 '.',
 'hardcore',
 ',',
 'classic',
 'use',
 'word.it',
 'called',
 'oz',
 'nickname',
 'given',
 'oswald',
 'maximum',
 'security',
 'state',
 'penitentary',
 '.',
 'focuses',
 'mainly',
 'emerald',
 'city',
 ',',
 'experimental',
 'section',
 'prison',
 'cells',
 'glass',
 'fronts',
 'face',
 'inwards',
 ',',
 'privacy',
 'high',
 'agenda',
 '.',
 'em',
 'city',
 'home',
 'many',
 '..',
 'aryans',
 ',',
 'muslims',
 ',',
 'gangstas',
 ',',
 'latinos',
 ',',
 'christians',
 ',',
 'italians',
 ',',
 'irish',
 'more',
 '....',
 'so',
 'scuffles',
 ',',
 'death',


In [53]:
X = df.iloc[:,0:1]
Y = df['sentiment']

In [54]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production. filming technique...
2      thought wonderful way spend time hot summer we...
3      basically there's family little boy (jake) thi...
4      petter mattei's "love time money" visually stu...
...                                                  ...
49995  thought movie right good job. creative origina...
49996  bad plot, bad dialogue, bad acting, idiotic di...
49997  catholic taught parochial elementary schools n...
49998  i'm going disagree previous comment side malti...
49999  one expects star trek movies high art, fans ex...

[49582 rows x 1 columns]

In [55]:
Y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 49582, dtype: object

In [56]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)
Y

array([1, 1, 1, ..., 0, 0, 0])

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)

In [58]:
X_train

review
17824  got movie library, saw lot actors like it(john...
41082  may made hell it, probably worst film i've see...
35822  saw movie child. blew away. days television, m...
40     clichés movies type substance. plot went nowhe...
19775  cult starts 20 years ago 'quinling mountain ra...
...                                                  ...
44035  helps characters show based among best disney ...
32696  carlos mencia continually, violently, hatefull...
5195   lot horror fans seem love scarecrows, popular ...
12195  first 20 minutes, every cliche possible trotte...
33189  thought wasting precious 50 bucks going watch ...

[39665 rows x 1 columns]

In [182]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=20000)


In [183]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [184]:
X_train_bow.shape

(39665, 20000)

In [186]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,Y_train)

GaussianNB()

In [187]:
Y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(Y_test,Y_pred)


0.7027326812544116

In [188]:
confusion_matrix(Y_test,Y_pred)

array([[4423,  610],
       [2338, 2546]], dtype=int64)

In [189]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)
Y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test,Y_pred)

0.8547947968135525

In [190]:
confusion_matrix(Y_test,Y_pred)

array([[4305,  728],
       [ 712, 4172]], dtype=int64)

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features= 20000)

In [62]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review']).toarray()

In [67]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_tfidf,Y_train)
Y_pred = gnb.predict(X_test_tfidf)


In [68]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix(Y_test,Y_pred)

array([[4216,  817],
       [1598, 3286]], dtype=int64)

In [69]:
accuracy_score(Y_test,Y_pred)

0.7564787738227287

In [65]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,Y_train)
Y_pred = rf.predict(X_test_tfidf)
accuracy_score(Y_test,Y_pred)

0.8512655036805485

In [66]:
confusion_matrix(Y_test,Y_pred)

array([[4295,  738],
       [ 737, 4147]], dtype=int64)